name: Update Download Count

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Release Data
        id: fetch_release
        run: |
          release_data=$(curl -s https://api.github.com/repos/shupershuff/diablo2rloader/releases/latest | jq -c '.')
          echo "release_data=$release_data" >> $GITHUB_OUTPUT

      - name: Calculate Download Count
        id: calculate_downloads
        run: |
          release_data="${{ steps.fetch_release.outputs.release_data }}"
          echo "Fetched release data: $release_data"
          # Use jq to extract download_count from assets array
          download_count=$(echo "$release_data" | jq '[.assets[].download_count] | add')
          echo "download_count=$download_count" >> $GITHUB_OUTPUT

          # Check if download_count is empty or null
          if [ "$download_count" == "null" ] || [ -z "$download_count" ]; then
            echo "No download count found, setting to 0"
            download_count=0
          fi
          
          #echo "::set-output name=download_count::$download_count"
          echo "download_count=$download_count" >> $GITHUB_OUTPUT
      - name: Update JSON File
        run: |
          echo '{
            "schemaVersion": 1,
            "label": "downloads",
            "message": "'${{ steps.calculate_downloads.outputs.download_count }}'",
            "color": "blue"
          }' > .github/download-count.json

      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.ACTIONS_PUSH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/download-count.json
          git commit -m 'Update download count'
          git push https://$TOKEN@github.com/shupershuff/Diablo2RLoader.git HEAD:main
